# Assets configuration
# List of stocks and cryptocurrencies to track

crypto:
  - symbol: "BTC"
    name: "Bitcoin"
  - symbol: "ETH"
    name: "Ethereum"
  # Add more cryptocurrencies as needed

stocks:
  - symbol: AAPL
    name: Apple Inc.
    exchange: nasdaq
    start_date: 2023-01-01
    description: "Consumer electronics and services"
    tags: [tech, consumer]
    
  - symbol: NVDA
    name: NVIDIA Corporation
    exchange: nasdaq
    start_date: 2023-01-01
    description: "AI and graphics computing"
    tags: [tech, ai, semiconductors]