# General system settings
system:
  data_refresh_interval: 3600  # In seconds (1 hour)
  trade_confirmation: true
  max_allocation_per_asset: 0.20  # Maximum 20% of portfolio per asset

# YouTube channels to monitor
youtube:
  channels:
    - name: "Camel Finance"
      channel_id: "UCr_DLep7UQ0B_IFhvTORu8A"
      relevance: 9

# API configurations
apis:
  kucoin:
    sandbox_mode: false  # Set to false for real trading
    
  deepseek:
    model: "deepseek-r1-large"